### ISSUE TITLE
Errors that occur on pages that redirect.

### ISSUE THREAD

**Issue by k-s-h-r** [niieani/puppeteer-intercept-and-modify-requests#10]
The following error occurs on the redirected page
`ProtocolError: Protocol error (Fetch.getResponseBody): Can only get response body on requests captured after headers received.`

The error could be avoided by including 3XX in the StatusCode check.
`if (!responseStatusCode)` ->
`if (!responseStatusCode || responseStatusCode === 302) {`

**Comment by niieani** [comment]
Wanna file a PR with the fix? There's probably a few other status codes that don't expect a body.
