### ISSUE TITLE
Modification is not applied if a target document was to be opened via a link in new tab

### ISSUE THREAD

**Issue by JenieX** [niieani/puppeteer-intercept-and-modify-requests#12]
This is an example that shows the issue.

When opening the link (example.com) by mouse left click, it would work as normal. However, it would open the original (un-modified) document if it is to be opened in a new tab by mouse middle click, or by "Open link in new tab" from the context menu.
```js
const handlePage = async (page: Page | null): Promise<void> => {
  if (page !== null) {
    const client = await page.target().createCDPSession();
    const interceptManager = new RequestInterceptionManager(client);

    await interceptManager.intercept(
      {
        urlPattern: '*://example.com/*',
        resourceType: 'Document',
        async modifyResponse() {
          return { body: '<a href="./">example.com</a>' };
        },
      },
    );
  }
};

browser.on('targetcreated', async (target: Target) => {
  const page = await target.page();
  await handlePage(page);
});

const currentPages = await browser.pages();

for (const page of currentPages) {
  await handlePage(page);
}
```

Thank you for this project regardless. 😄

**Comment by niieani** [comment]
Hi @JenieX! Unfortunately, that's how request interception currently works in Chrome. If the target is opened with a URL, it's already too late to initiate interception for the `Document` resource type. 
You might be able to figure out a workaround for this though.

**Comment by JenieX** [comment]
> Hi @JenieX! Unfortunately, that's how request interception currently works in Chrome. If the target is opened with a URL, it's already too late to initiate interception for the `Document` resource type. You might be able to figure out a workaround for this though.

I did actually. First was using a pha script on my local server that redirects to the link after one second, then I switched to embedding data directly in a URL using the data URI scheme. Which later I further took advantage of by setting the the page to only load after gaining focus. 😄

```html
<!-- loader template -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Waiting focus..</title>
    <script>
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') {
          location.href = '{target}';
        }
      });
    </script>
  </head>
  <body style="background: black"></body>
</html>

```
```js
const link = `data:text/html;charset=utf-8,${encodeURIComponent(minLoaderDocument)}`;
```

Can you think of a better way?

**Comment by niieani** [comment]
Yes @JenieX ! Turns out you can just pass in the Browser CDP session client, instead of a single Page, and you can setup interception for the entire Chrome.

See my [updated readme here](https://github.com/niieani/puppeteer-intercept-and-modify-requests#intercepting-network-requests-from-all-pages-rather-than-just-the-one).

**Comment by JenieX** [comment]
> Yes @JenieX ! Turns out you can just pass in the Browser CDP session client, instead of a single Page, and you can setup interception for the entire Chrome.
> 
> See my [updated readme here](https://github.com/niieani/puppeteer-intercept-and-modify-requests#intercepting-network-requests-from-all-pages-rather-than-just-the-one).

Super awesome. 😃
