### ISSUE TITLE
Response stage is recognized as request stage

### ISSUE THREAD

**Issue by jacksky007** [niieani/puppeteer-intercept-and-modify-requests#29]
Hi. Thanks for your tool which is helping me a lot these days. I'm facing an edge case when I get the response from the server the response code is absent. The code below treats it at request stage, but in fact it is at response stage.

```
      if (!responseStatusCode) {
        // handling a request
```
> https://github.com/niieani/puppeteer-intercept-and-modify-requests/blob/main/src/main.ts#L136

Can we do some minors change to the code,

1. change the condition to ``` if (modifyRequest && !responseStatusCode)```
2. give the response code a fallback value to 200
change this ```responseCode: responseStatusCode,``` to ````responseCode: responseStatusCode || 200,```
> https://github.com/niieani/puppeteer-intercept-and-modify-requests/blob/main/src/main.ts#L202

Thanks again if you can update as above or if you have better solution for such edge case.

**Comment by niieani** [comment]
Hi @jacksky007!
Thanks for your report. I'm glad the tool is helpful!
I will release a fix soon.
