### ISSUE TITLE
Support running in browser extension

### ISSUE THREAD

**Issue by lwintermelon** [niieani/puppeteer-intercept-and-modify-requests#32]
https://github.com/niieani/puppeteer-intercept-and-modify-requests/blob/2dc2c26954678d12af765ffa1980873ec4e82ab9/src/main.ts#L70-L74

Take a CDPSession as client may not be so universal (It seems that we can't get a CDPSession from `page.createCDPSession()` in browser context), as we only need `on`, `off`, and `send` method. I see `ExtensionTransport` is implemented in extension context, but how to connect it to client of `RequestInterceptionManager `, any advice or I miss something already availiable?

**Comment by niieani** [comment]
Assuming you're using https://github.com/gajananpp/puppeteer-extension-transport#usage, you should still be able to create a CDPSession:

```ts
const extensionTransport = await ExtensionDebuggerTransport.create(tabId)
const browser = await puppeteer.connect({
    transport: extensionTransport,
    defaultViewport: null,
})

const client = await browser.target().createCDPSession()
const interceptManager = new RequestInterceptionManager(client)
```

**Comment by lwintermelon** [comment]
I am following [Running Puppeteer in Chrome extensions](https://pptr.dev/guides/running-puppeteer-in-extensions), note they provide offical support for running Puppeteer in Chrome extensions, though it is currently experimental. `page.createCDPSession()` will finally get an error after it takes a long time, I'll try to debug the function for more information, or maybe fire a issue on Puppeteer.

**Comment by niieani** [comment]
What's the error you get on `createCDPSession`?

Looks like `ExtensionTransport` has a send method, but it only accepts stringified messages. It might be impossible to get this working without some additional implementation work to create an abstraction layer for a fake CDPSession in Chrome Extensions.

**Comment by lwintermelon** [comment]
When `const target = await page.createCDPSession();` runs, it fails and fires the log below.
```
// error log for `const target = await page.createCDPSession();`
puppeteer:protocol:SEND ►: {"method":"Target.attachToTarget","params":{"targetId":"pageTargetId","flatten":true},"id":5}
puppeteer:protocol:RECV ◀: {"id":5,"sessionId":"pageTargetSessionId","method":"Target.attachToTarget","error":{"message":"{\"code\":-32000,\"message\":\"Not allowed\"}"}}
```
The debug ability for extension is provided by [chrome.debugger api](https://developer.chrome.com/docs/extensions/reference/api/debugger), it's attached by tabId like `chrome.debugger.attach({tabId}, '1.3')`, it's diffirent from normal CDP connection(a Browser context can have multiple pages). Can we get a new session for a pageTarget? What's the restriction for Chrome?

I file an [issue](https://github.com/puppeteer/puppeteer/issues/13251) on Puppeteer. Technically we can get or make a fake CDPSession, even from same session as puppeteer.

**Comment by niieani** [comment]
I know Puppeteer used to have a property `.target()` that you could call on Page (`page.target()`), but I think it's been deprecated. Not sure if it still works though, feel free to try it. You could then possibly pass that target to this library instead of the CDP session.
