### ISSUE TITLE
Mock response but don't request server

### ISSUE THREAD

**Issue by JxxIT** [niieani/puppeteer-intercept-and-modify-requests#34]
Hi, 

Is it possible to mock the response without it requesting the server?
I looked at the docs, but I can't find it anywhere.

Thanks!

**Comment by niieani** [comment]
Hi @JxxIT !

Yes, it's possible. Use `modifyRequest`, as per docs:

> You may modify the request itself, before it is sent to the server, by adding a `modifyRequest` function.

**Comment by JxxIT** [comment]
Thanks @niieani!

I meant to fake a response without requesting the original server. For example: I am trying to fake the response of a signup page, but I don't want the server actually signing me up.

Is that possible? Thanks!

**Comment by JxxIT** [comment]
I can get this working with the normal puppeteer requestInterception, but I really want to use this great library!

```
await page.setRequestInterception(true);

page.on('request', request => {
    if (request.url().includes("example.com/api")) {
        request.respond({
            headers: { "Access-Control-Allow-Origin": "*" },
            body: 'test',
        });
    } else {
        request.continue();
    }
});
```

**Comment by niieani** [comment]
Yes, you can do it with this library, if you use modifyRequest it will not send the request to the server unless you want it to. You can respond with whatever mock data you want without having it call a backend.

**Comment by JxxIT** [comment]
I did that, with a POST request, but it still signed me up. Am I doing something wrong?

**Comment by niieani** [comment]
can you post a code snippet showing how you set it up?

**Comment by JxxIT** [comment]
This logs the requests made to the server, and if it was intercepted by the lib or the native implementation.

```
import { launch } from 'puppeteer';
import express from 'express';
import cors from 'cors';
const app = express()
const port = 3000
import path from 'path';
const __dirname = path.resolve();
import { RequestInterceptionManager } from 'puppeteer-intercept-and-modify-requests';

app.use(express.json());
app.use(express.urlencoded({
    extended: true
}));
app.use(cors());
app.options('*', cors());

app.post('/post/:calledFrom', (req, res) => {
    console.log(`Recieved POST request from ${req.params.calledFrom}`);
    res.status(200).send("ok");
})

app.get('/', (req, res) => {
    res.set('Content-Type', 'text/html');
    res.status(200).send(new Buffer(`
        <script>
            (async () => {
                const rawResponse = await fetch('http://localhost:3000/post/lib', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: "{}"
                });
                document.body.innerHTML += '<br>' + await rawResponse.text();
            })();

            (async () => {
                const rawResponse = await fetch('http://localhost:3000/post/native', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: "{}"
                });
                document.body.innerHTML += '<br>' + await rawResponse.text();
            })();
        </script>
    `));
})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})


let browser = await launch({
    headless: false,
});

let page = await browser.newPage();

const client = await page.target().createCDPSession()

const interceptManager = new RequestInterceptionManager(client)

await interceptManager.intercept(
    {
        urlPattern: `http://localhost:3000/post/lib`,
        modifyResponse({ body }) {
            return {
                body: 'Replaced by interceptManager',
            }
        },
    }
)

await page.setRequestInterception(true);

page.on('request', request => {
    if (request.url() == "http://localhost:3000/post/native") {
        request.respond({
            headers: { "Access-Control-Allow-Origin": "*" },
            body: 'Replaced by setRequestInterception',
        });
    } else {
        request.continue();
    }
});


await page.goto('http://localhost:3000');
```

**Comment by niieani** [comment]
In your example, you're using `modifyResponse` not `modifyRequest`. This is why the InterceptionManager still passes through the request. If you don't want any requests to the backend, use `modifyRequest` instead.
Also, you shouldn't mix `InterceptionManager` with `await page.setRequestInterception(true);` and `page.on('request', ...)` as it can cause issues. Use either one or the other.

**Comment by JxxIT** [comment]
Sorry, I don't really understand.
Can you give me an example on how I could use the `modifyRequest` function? The `modifyRequest` function only changes the request right? I want to reply, without any code (including the package) to reach the server.

I only mixed those two to test if it worked with Puppeteer's native request interception.

**Comment by niieani** [comment]
see the new section in the readme file https://github.com/niieani/puppeteer-intercept-and-modify-requests#stubbing-responses-at-request-time

**Comment by JxxIT** [comment]
Great! Thank you so much for your time!
